for caro
mihi314/dotfiles pull request #1
Opened 2019-01-15 20:24 UTC by mihi314

2019-01-15 21:05 UTC, lacinoire requested changes
Joa ganz solide, gefällt mir, ist ordentlich geschrieben.

Weißt du es gibt da so ganz neuen heißen Scheiß bei uns in der Softwareentwicklung... Haben noch nich alle übernommen aber man munkelt, sogar Python hätte in 3.6 oder 3.7 "Typen" eingeführt 🧐 Diese "Typen" sind voll super nice, die sagen dir nämlich so ein bisschen was da für Daten rein- und rauskommen aus so ner Methode 😵 dann hat man nicht nur den Namen für die Semantik sondern auch was für die Syntax, voll krass. Solltest du dir mal ankucken, zumindest wenn du so Code schreibst den neue  Mitarbeiter oder Zukunfts-Michis mal warten sollen 😜

2019-01-15 21:05 UTC, lacinoire commented on bin/match_filenames.py
> +        A regular expression whose matches define equivalence classes. If there are subgroups, use those. If there is
wer soll die benutzten die subgruppen? ich oder der Algorithmus? klingt etwas nach ich aber dann frage ich mich direkt, wie ich die denn benutzen soll 😃

2019-01-15 21:05 UTC, lacinoire commented on bin/match_filenames.py
> +    # sort each filename into a class
hier wäre ein Doc-kommentar gut

2019-01-15 21:05 UTC, lacinoire commented on bin/match_filenames.py
> +        # todo: add nicer error message when the regexp is invalid
nach genereller Konvention würde man hier `TODO:` schreiben, im Team mit eingeklammertem Namenskürzel dahinter

2019-01-15 21:05 UTC, lacinoire commented on bin/match_filenames.py
> +    return it.chain.from_iterable(list_of_lists)
einzeilige Methode auslagern, die nur einmal aufgrufen wird... könnte man jetzt diskutieren ob sich das lohnt.
z.B. auch ob das jemand wiederfinden würde wenn er eine ähnliche Funktionalität braucht.
Ist aber schön benannt, das könnte ein Argument sein.

Wenns nur einmal verwendet wird sollte es auch nah an dieser Verwendung deklariert werden, macht es einfacher sich zurecht zu finden.

2019-01-15 21:05 UTC, lacinoire commented on bin/match_filenames.py
> +            os.makedirs(target, exist_ok=True)
was macht das? kucken ob der Zielordner existiert? wäre das dann außerhalb der Loop vielleicht besser aufgehoben?

2019-01-15 21:05 UTC, lacinoire commented on bin/match_filenames.py
> +              help="(path, pattern) tuple. path can be a directory or a text file. pattern is a regular "
Sätze müssen mit Großbuchstaben anfangen 😄

2019-01-15 21:05 UTC, lacinoire commented on bin/match_filenames.py
> +@click.option("-t", "--target", type=click.Choice(["diff", "int"]), default="diff",
diff / int kann ich jetzt nicht auf move / delete mappen 🧐

2019-01-15 21:05 UTC, lacinoire commented on bin/match_filenames.py
> +              help="whether to delete the difference or intersection")
ohhhh

2019-01-15 21:05 UTC, lacinoire commented on bin/match_filenames.py
> +              help="whether to delete the difference or intersection")
vielleicht oben: whether to calculate the difference or the intersection

2019-01-15 21:05 UTC, lacinoire commented on bin/match_filenames.py
> +              help="whether to delete the difference or intersection")
und dann hier 
```suggestion
              help="whether to delete the resulting files")
```
oder so in der Richtung

2019-01-15 21:05 UTC, lacinoire commented on bin/match_filenames.py
> +              help="whether to move the difference or intersection to a separate folder/file called "
ist auch nicht so wirklich ein entweder oder hier (das "whether" suggeriert das aber)
bei flags kannst du das whether vielleicht auch weglassen in der Beschreibung

2019-01-15 21:05 UTC, lacinoire commented on bin/match_filenames.py
> +    them or the remaining ones (the "difference"). Can be used to make the different directories match, or to make them
sehr schön formuliert 🤗

2019-01-15 21:05 UTC, lacinoire commented on bin/match_filenames.py
> +    print("int: equivalence classes present in all directories ({}):".format(len(intersection)))
all weißt du? ebenso mit dem some unten 🤔

2019-01-15 21:05 UTC, lacinoire commented on bin/match_filenames.py
> +        if target == "diff":
das "diff" könnte man, wenn man ganz fancy sein will in eine Konstante tun
"int" dann ebenso

2019-02-13 16:24 UTC, mihi314 commented on bin/match_filenames.py
> +            os.makedirs(target, exist_ok=True)
definitiv :sweat_smile:

2020-02-22 07:55 UTC, closed without merging